### ISSUE TITLE
start hugo error: ENOENT

### ISSUE THREAD

**Issue by shanquan** [shanquan/one-click-hugo-cms#1]
**- window 10, victor-hugo@1.0.0 **

`npm install` completed and then `npm start` with errors as follow:

> victor-hugo@1.0.0 start D:\wwl\Develop\git\github\one-click-hugo-cms
> run-p start:**

> victor-hugo@1.0.0 start:webpack D:\wwl\Develop\git\github\one-click-hugo-cms
> webpack-dev-server --config webpack.dev.js --hot

> victor-hugo@1.0.0 start:hugo D:\wwl\Develop\git\github\one-click-hugo-cms
> hugo -d ../dist -s site -vw

events.js:288
      throw er; // Unhandled 'error' event
      ^

Error: spawn D:\wwl\Develop\git\github\one-click-hugo-cms\node_modules\hugo-bin\vendor\hugo.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:273:12)
    at onErrorNT (internal/child_process.js:469:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn D:\\wwl\\Develop\\git\\github\\one-click-hugo-cms\\node_modules\\hugo-bin\\vendor\\hugo.exe',
  path: 'D:\\wwl\\Develop\\git\\github\\one-click-hugo-cms\\node_modules\\hugo-bin\\vendor\\hugo.exe',
  spawnargs: [ '-d', '../dist', '-s', 'site', '-vw' ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start:hugo: `hugo -d ../dist -s site -vw`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start:hugo script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\wang.weili\AppData\Roaming\npm-cache\_logs\2020-04-08T01_07_57_882Z-debug.log
ERROR: "start:hugo" exited with 1.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! victor-hugo@1.0.0 start: `run-p start:**`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the victor-hugo@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by shanquan** [comment]
copy `bin/hugo.exe` and paste to `node_modules/hugo-bin/vendor/hugo.exe`.  Then run with`npm start`, solves the problem.
